### ISSUE TITLE
`clientConnect` consistently fails with `Prelude.read: no parse`

### ISSUE THREAD

**Issue by cab404** [kazu-yamamoto/network-udp#1]
And nope, it is not originating from reading either address or port

```
ghci> import qualified Network.UDP as NU
ghci> NU.clientSocket (read "0.0.0.0") (read "1111") True
*** Exception: Prelude.read: no parse
```

**Comment by kazu-yamamoto** [comment]
Why do you use `read`?

The following is an example of proper usage:

```
> clientSocket "0.0.0.0" "1111" True
UDPSocket {udpSocket = <socket: 13>, peerSockAddr = 0.0.0.0:1111, connected = True}
```

**Comment by cab404** [comment]
Ooof, sorry about that! 
I've reused it from other part of a program, and since the types matched, I didn't pay much attention, and improperly checked reads D:

**Comment by cab404** [comment]
(and also because reads are required with serverSocket)
